### ISSUE TITLE
add umso

### ISSUE THREAD

**Issue by smknstd** [smknstd/privacy-focused-analytics#13]
https://www.umso.com/analytics

**Comment by sid-r-singh** [comment]
@smknstd , Umso looks interesting. But I don't know whether the analytics is a standalone offering or not. I guess it's coupled with their website builder/hosting service, since their tagline says "The Website Builder for Startups".

**Comment by smknstd** [comment]
I think you're right ! As it is not a standalone analytics product, I close this issue. Thanx for your work. Have a good day !
