### ISSUE TITLE
Offen and consent / cookies requirements

### ISSUE THREAD

**Issue by m90** [smknstd/privacy-focused-analytics#3]
Hi! I am one of the authors of [Offen](https://github.com/offen/offen). Thank you for featuring us on this website.

---

About this headline:

> A collaborative list of website analytics that don't use cookie, don't require consent and focus on privacy.

Offen does not meet your established requirements as a. Offen will always require user consent before collecting data (to us, this is a prerequisite for calling something "privacy focused") and b. Offen uses cookies (cookies come with a lot of privacy perks once you have accepted the fact that they require consent).

It's not up to us to define how you curate your collection, so if you want to stick to your initial criteria it'd might be best to remove Offen again, however we'd like to stress that neither requiring user consent nor using cookies are a bad thing for privacy focused tools (we'd argue they are beneficial if used correctly) so maybe extending your criteria and filtering options would also be an idea?

**Comment by smknstd** [comment]
Thanks for pointing this. I added a new "cookie free" filter:

![Screenshot from 2021-01-02 19-11-06](https://user-images.githubusercontent.com/2412608/103463683-6dbefe80-4d2e-11eb-9d44-eff7a0431e72.png)
