### ISSUE TITLE
Consider making Github link clearer

### ISSUE THREAD

**Issue by alexkreidler** [smknstd/privacy-focused-analytics#5]
Because the "Website" and "Demo" links have a clear link icon next to them, and the Github icon doesn't look clickable, I didn't even realize it was a link, so I went to each tool's site and then found the Github link from there.

It would be great to just have "Github" be another link in the list of links, or for it to have the link SVG icon next to it to show it is clickable.

Thanks for this cool project!

**Comment by smknstd** [comment]
Great feedback ! I'll try something out.

**Comment by smknstd** [comment]
not beautiful but better than before I hope:

![Screenshot_2021-04-22 Privacy Focused Analytics](https://user-images.githubusercontent.com/2412608/115745900-28354880-a394-11eb-8486-760881f9141e.png)
